function [bnet ll] = learn_bnet(bnet0, cases)

engine = smoother_engine(jtree_2TBN_inf_engine(bnet0));
%engine = hmm_inf_engine(bnet0);
%engine = bk_inf_engine(bnet0, 'clusters', 'ff');
%engine = smoother_engine(jtree_dbn_inf_engine(bnet0));
%engine = smoother_engine(hmm_2TBN_inf_engine(bnet0));
    
[bnet ll] = learn_params_dbn_em( ...
		engine, ...
		cases, ...
		'max_iter', 50, ...
		'thresh', 1e-3, ...
		'verbose', 0, ...
		'anneal', 1, ...
		'anneal_rate', 0.8, ...
		'init_temp', 10, ...
		'final_temp', 1);
